### ISSUE TITLE
Sugestão de alterações

### ISSUE THREAD

**Issue by bindwkill** [rafael-arashiro/pi1-bti-22#12]
#### entrada.html
```html
<p><a href="{{ url_for('logoff') }}">Sair</a></p>
```
_não sei se tem outro jeito de "deslogar" então estou sugerindo que seja adicionada a opção_

#### css.css
```css
a {
    background: lavenderblush;
    border: 1px solid;
    padding: 2px 2px 2px 2px;
    border-radius: 4px;
    text-decoration: none;
}
```
_isso vai deixar os links da entrada parecendo botõezinhos sem modificar o layout_

* Trocar a classe '.titulo' pela tag 'h1' (ou remover)
* Remover as classes '.form-container' e .form-group

_Acho que elas não estão sendo mais usadas e só sugeri de adicionar porque tenho TOC de deixar tudo no centro_

```css
table {
  border-collapse: collapse;
  width: 80%;
  background: floralwhite;
}
```
_Acho que uma cor ligeiramente diferente do fundo da página deve deixar mais agradável a leitura da tabela, fica essa como sugestão mas poderia ser qualquer outra que não contraste muito com o fundo_
